---
# Gitpod Configuration
# ver: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

# Uso de imagen de Docker específica
# ver: https://hub.docker.com/u/gitpod
# image: gitpod/workspace-full-vnc
# image:
#   file: Dockerfile
image: jchavarr/gitpod-featureide

ports:
  - port: 6080
    visibility: private


# Comandos a ejecutar al inicio del proyecto
# tasks:
#
#  - name: Ejecuta FeaureIDE
#    command: /opt/eclipse/eclipse -data ./workspace &

# Extensiones
vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

  