---
# Gitpod Configuration
# ver: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

# Uso de imagen de Docker específica
# ver: https://hub.docker.com/u/gitpod

# image:
#   file: Dockerfile
image: jchavarr/gitpod-featureide

ports:
  - port: 6080
    visibility: private

# Comandos a ejecutar al inicio del proyecto
tasks:
  - name: Ejecuta FeaureIDE
    command: |
      gp preview --external $(gp url 6080)
      ./ejecuta-eclipse.sh

# Extensiones
vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

  